name: itvapp_live_tv  # 应用程序的名称，可以根据需要进行更改。
description: 电视宝 www.itvapp.net 直播，支持Android、车机、电视！ # 应用的描述信息。
publish_to: "none"  # 私有项目不发布到pub.dev。如果要将包发布到pub.dev，将此行删除或修改为有效的URL。
version: 1.5.8+1  # 应用的版本号，格式为 "主版本.次版本.修订版本+构建号"。 

environment:
  sdk: ">=3.8.0 <4.0.0"  # Dart SDK的版本
  flutter: ">=3.27.0"

dependencies:
  youtube_explode_dart: 2.4.2  # 用于从 YouTube 获取视频信息和下载视频的库。
  flutter:
    sdk: flutter  # Flutter SDK的依赖，用于开发Flutter应用。
  flutter_localizations:
    sdk: flutter  # Flutter的本地化支持库，用于多语言和地区设置的支持。
  
  # 使用iapp_player
  iapp_player:
    path: ./packages/iapp_player  # 指向本地iapp_player目录
  
  flutter_animate: 4.5.2  # 图片切换动画效果
  marquee: 2.3.0  # 文字跑马灯效果
  responsive_builder: 0.7.1  # 响应式布局工具，帮助实现不同屏幕尺寸下的自适应布局。
  flutter_easyloading: 3.0.5  # 提供简单的加载动画，常用于请求或长时间操作的过渡显示。
  wakelock_plus: 1.3.2  # 保持屏幕常亮的插件，适用于需要长时间显示内容的应用。
  # geolocator: 14.0.1  # 地理定位插件。
  # geolocator_android: 5.0.1+1  # 地理定位插件
  # geocoding: 3.0.0  # 地理编码插件。
  dio: 5.7.0  # 网络请求库，功能强大，支持拦截器、请求取消等。
  brotli: ^0.6.0  # 使用Brotli压缩的网站时，返回的内容将被正确解码
  sp_util: 2.0.3  # SharedPreferences工具类，简化数据存储操作，适用于存储应用配置等小数据。
  url_launcher: 6.3.1  # 打开外部URL的插件，支持网页、邮件、电话等链接的调用。
  flutter_volume_controller: 1.3.3  # 音量控制插件，用于控制设备音量。
  screen_brightness: 2.1.1  # 屏幕亮度控制插件，允许调整屏幕亮度。
  pretty_qr_code: 3.3.0  # 生成二维码的插件，支持多种二维码样式。
  intl: ^0.19.0  # 国际化支持库，用于支持多语言环境和格式化日期、时间等。
  path_provider: 2.1.5  # 查找文件系统路径的插件，常用于存储文件在设备中的路径。
  provider: 6.1.2  # 状态管理库，用于管理应用状态，适用于复杂应用的状态处理。
  flutter_exit_app: 1.1.4  # 用于退出应用程序的插件，适合在需要强制退出应用的场景。
  xml: 6.6.0  # XML解析库，用于解析和处理XML格式的数据。
  apk_installer: 0.0.4  # 用于安装 APK 文件的插件，适用于 Android 应用。
  device_info_plus: 11.2.1  # 获取设备信息的插件，可以获取设备型号、操作系统等信息。
  webview_flutter: 4.13.0  # 模拟网页访问。
  crypto: 3.0.6   # 处理sha256签名。
  encrypt: 5.0.3   # 处理加密/解密（如 AES）。
  # file_picker: 8.1.2  # 文件选择器插件，允许用户选择文件，适用于文件上传等场景。

dev_dependencies:
  flutter_test:
    sdk: flutter  # 用于Flutter测试的依赖。
  flutter_lints: 4.0.0  # Flutter代码风格和检查规则

flutter:
  uses-material-design: true  # 是否启用Material Design。
  generate: true
  assets:
    - assets/images/
    - assets/js/
    - assets/playlists.m3u

flutter_intl:
  enabled: true  # 是否启用Flutter的国际化支持。
  arb_dir: lib/l10n  # 国际化文件的目录路径，可根据实际需要修改。
  class_name: S  # 自动生成的国际化类的名称。
  main_locale: en  # 应用的主语言区域设置
