name: itvapp_live_tv  # 应用程序的名称，可以根据需要进行更改。

description: 电视宝 www.itvapp.net 直播，支持Android、车机、电视！
# 应用的描述信息，这段文字通常会显示在应用商店中。可以根据项目实际情况进行修改。

publish_to: "none"  # 私有项目不发布到pub.dev。
# 如果要将包发布到pub.dev，将此行删除或修改为有效的URL。

version: 1.5.8+1  # 应用的版本号，格式为 "主版本.次版本.修订版本+构建号"。 
# 可以根据版本发布策略修改。例如，版本号可设置为 1.0.0+1。

environment:
  sdk: ">=3.4.0 <4.0.0"  # Dart SDK的版本约束。可以根据项目需要选择不同版本的SDK。

dependencies:
  youtube_explode_dart: ^2.2.1
  flutter:
    sdk: flutter  # Flutter SDK的依赖。
  flutter_localizations:
    sdk: flutter  # 国际化支持的依赖。

  # 以下是应用所需的第三方库依赖，您可以根据实际需要添加、删除或更新这些依赖的版本。
  http: ^1.2.2
  fvp: ^0.26.1  # 视频播放器插件的依赖。
  video_player: ^2.9.1  # 视频播放库，版本号可根据需要修改。
  responsive_builder: ^0.7.1  # 响应式布局工具。
  flutter_easyloading: ^3.0.3  # 简单的加载动画库。
  wakelock_plus: ^1.2.5  # 保持屏幕常亮的插件。
  flutter_spinkit: ^5.1.0  # 加载动画库。
  dio: ^5.5.0+1  # 网络请求库，用于发起HTTP请求。
  sp_util: ^2.0.3  # SharedPreferences工具，用于数据存储。
  url_launcher: ^6.3.0  # 用于打开URL的插件。
  flutter_volume_controller: ^1.3.2  # 音量控制插件。
  screen_brightness: ^1.0.1  # 屏幕亮度控制插件。
  pretty_qr_code: ^3.3.0  # 生成二维码的插件。
  window_manager: ^0.4.2  # 窗口管理插件，用于桌面应用。
  intl: ^0.19.0  # 国际化支持库，用于多语言支持。
  scrollable_positioned_list: ^0.3.8  # 可滚动的定位列表。
  path_provider: ^2.1.4  # 用于查找文件系统路径的插件。
  provider: ^6.1.2  # 状态管理库，用于应用状态管理。
  xml: ^6.5.0
  apk_installer: ^0.0.4
  is_tv: ^0.0.1+3
  device_info_plus: ^10.1.2
  # file_picker: ^8.1.2  # 文件选择器插件。
  # shared_preferences: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter  # 用于Flutter测试的依赖。

  flutter_lints: ^4.0.0  # 推荐的Flutter代码风格和检查规则，您可以修改或替换这个配置。

flutter:
  uses-material-design: true  # 是否启用Material Design。一般保持为true。
  generate: true

  assets:
    - assets/images/  # 资源文件路径，可根据项目实际情况添加其他资源路径。

flutter_intl:
  enabled: true  # 是否启用Flutter的国际化支持。
  arb_dir: lib/l10n  # 国际化文件的目录路径，可根据实际需要修改。
  class_name: S  # 自动生成的国际化类的名称。
  main_locale: en  # 应用的主语言区域设置
