name: itvapp_live_tv  # 应用程序的名称，可以根据需要进行更改。

description: 电视宝 www.itvapp.net 直播，支持Android、车机、电视！
# 应用的描述信息，这段文字通常会显示在应用商店中。可以根据项目实际情况进行修改。

publish_to: "none"  # 私有项目不发布到pub.dev。
# 如果要将包发布到pub.dev，将此行删除或修改为有效的URL。

version: 1.5.8+1  # 应用的版本号，格式为 "主版本.次版本.修订版本+构建号"。 
# 可以根据版本发布策略修改。例如，版本号可设置为 1.0.0+1。

environment:
  sdk: ">=3.4.0 <4.0.0"  # Dart SDK的版本约束。可以根据项目需要选择不同版本的SDK。

dependencies:
  youtube_explode_dart: ^2.3.5  # 用于从 YouTube 获取视频信息和下载视频的库。
  flutter:
    sdk: flutter  # Flutter SDK的依赖，用于开发Flutter应用。
  flutter_localizations:
    sdk: flutter  # Flutter的本地化支持库，用于多语言和地区设置的支持。

  # 以下是应用所需的第三方库依赖，您可以根据实际需要添加、删除或更新这些依赖的版本。
  http: ^1.2.2  # 用于发起 HTTP 请求的库。
  video_player: ^2.9.2  # Flutter的官方视频播放库，用于播放视频内容。
  just_audio: ^0.9.42  # 用于播放音频内容。
  flutter_vlc_player: ^7.4.2  # 视频播放库，用于播放视频内容。
  responsive_builder: ^0.7.1  # 响应式布局工具，帮助实现不同屏幕尺寸下的自适应布局。
  flutter_easyloading: ^3.0.3  # 提供简单的加载动画，常用于请求或长时间操作的过渡显示。
  wakelock_plus: ^1.2.8  # 保持屏幕常亮的插件，适用于需要长时间显示内容的应用。
  flutter_spinkit: ^5.2.1  # 加载动画库，提供各种动画效果，增强用户体验。
  dio: ^5.7.0  # 网络请求库，功能强大，支持拦截器、请求取消等。
  sp_util: ^2.0.3  # SharedPreferences工具类，简化数据存储操作，适用于存储应用配置等小数据。
  url_launcher: ^6.3.1  # 打开外部URL的插件，支持网页、邮件、电话等链接的调用。
  flutter_volume_controller: ^1.3.2  # 音量控制插件，用于控制设备音量。
  screen_brightness: ^2.0.0+2  # 屏幕亮度控制插件，允许调整屏幕亮度。
  pretty_qr_code: ^3.3.0  # 生成二维码的插件，支持多种二维码样式。
  window_manager: ^0.4.2  # 桌面应用的窗口管理插件，允许操作窗口大小、位置等。
  intl: ^0.19.0  # 国际化支持库，用于支持多语言环境和格式化日期、时间等。
  scrollable_positioned_list: ^0.3.8  # 可滚动的定位列表插件，允许直接跳转到列表中的指定位置。
  path_provider: ^2.1.5  # 查找文件系统路径的插件，常用于存储文件在设备中的路径。
  provider: ^6.1.2  # 状态管理库，用于管理应用状态，适用于复杂应用的状态处理。
  flutter_exit_app: ^1.1.4  # 用于退出应用程序的插件，适合在需要强制退出应用的场景。
  xml: ^6.5.0  # XML解析库，用于解析和处理XML格式的数据。
  apk_installer: ^0.0.4  # 用于安装 APK 文件的插件，适用于 Android 应用。
  device_info_plus: ^11.1.1  # 获取设备信息的插件，可以获取设备型号、操作系统等信息。
  # file_picker: ^8.1.2  # 文件选择器插件，允许用户选择文件，适用于文件上传等场景。
  # shared_preferences: ^2.0.15  # 简单的本地存储插件，适用于存储少量数据，如用户偏好设置等。
  
dev_dependencies:
  flutter_test:
    sdk: flutter  # 用于Flutter测试的依赖。

  flutter_lints: ^4.0.0  # 推荐的Flutter代码风格和检查规则，您可以修改或替换这个配置。

flutter:
  uses-material-design: true  # 是否启用Material Design。一般保持为true。
  generate: true

  assets:
    - assets/images/  # 资源文件路径，可根据项目实际情况添加其他资源路径。

flutter_intl:
  enabled: true  # 是否启用Flutter的国际化支持。
  arb_dir: lib/l10n  # 国际化文件的目录路径，可根据实际需要修改。
  class_name: S  # 自动生成的国际化类的名称。
  main_locale: en  # 应用的主语言区域设置
