name: Generate-i18n-files
# 需要有仓库的写入权限：
# 点击 Settings > Actions > General > Workflow permissions
# 选择 Read and write permissions
# 选择读取和写入权限（默认可能是"读取仓库内容权限"）
# 点击 Save 保存更改
on:
  workflow_dispatch:  # 仅支持手动触发
permissions:
  contents: write  # 授予写权限以推送更改
jobs:
  generate-i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      
      - uses: subosito/flutter-action@v2  
        # 设置 Flutter 环境
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Setup i18n environment  
        # 设置国际化环境
        run: |
          echo "Setting up i18n environment..."
          # 确保 intl 包已经安装
          flutter pub add intl
          # 确保 flutter_localizations 包已经安装在 pubspec.yaml 中
          if ! grep -q "flutter_localizations:" pubspec.yaml; then
            echo "Adding flutter_localizations dependency to pubspec.yaml"
            sed -i '/dependencies:/a \ \ flutter_localizations:\n \ \ \ \ sdk: flutter' pubspec.yaml
          fi
          # 运行 flutter pub get 以确保所有依赖都已安装
          flutter pub get
      
      - name: Create or update l10n config  
        # 创建或更新国际化配置文件
        run: |
          set -e  # 修改：添加 set -e，确保命令失败时退出
          echo "Current working directory: $(pwd)"  # 修改：添加路径调试信息
          
          # 检查是否已存在 l10n.yaml 文件，如果不存在则创建
          if [ ! -f "l10n.yaml" ]; then
            echo "Creating l10n.yaml file"
            cat > l10n.yaml << 'EOL' || { echo "Failed to create l10n.yaml"; exit 1; }  # 修改：使用 'EOL' 避免变量替换，添加错误检查
          arb-dir: lib/l10n
          template-arb-file: intl_en.arb
          output-localization-file: app_localizations.dart
          EOL
            echo "Successfully created l10n.yaml"  # 修改：添加成功确认
          else
            echo "l10n.yaml already exists"  # 修改：添加已存在时的提示
          fi
          
          # 创建 lib/l10n 目录（如果不存在）
          mkdir -p lib/l10n || { echo "Failed to create lib/l10n directory"; exit 1; }  # 修改：添加错误检查
          echo "Successfully ensured lib/l10n directory"  # 修改：添加成功确认
          
          # 初始化 .arb 文件，仅在不存在时创建，并添加基本的 @@locale 字段
          [ ! -f lib/l10n/intl_en.arb ] && echo '{"@@locale": "en"}' > lib/l10n/intl_en.arb || { echo "Failed to create lib/l10n/intl_en.arb"; exit 1; }  # 修改：添加错误检查
          [ ! -f lib/l10n/intl_zh_CN.arb ] && echo '{"@@locale": "zh_CN"}' > lib/l10n/intl_zh_CN.arb || { echo "Failed to create lib/l10n/intl_zh_CN.arb"; exit 1; }  # 修改：添加错误检查
          [ ! -f lib/l10n/intl_zh_TW.arb ] && echo '{"@@locale": "zh_TW"}' > lib/l10n/intl_zh_TW.arb || { echo "Failed to create lib/l10n/intl_zh_TW.arb"; exit 1; }  # 修改：添加错误检查
          echo "Successfully ensured .arb files"  # 修改：添加成功确认
        shell: bash  # 修改：使用合法的 shell 值 'bash'，移除无效的 /usr/bin/bash -e {0}
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.24.0-x64  # 未修改：保留原始环境变量
          PUB_CACHE: /home/runner/.pub-cache  # 未修改：保留原始环境变量
      
      - name: Generate localization files  
        # 生成国际化文件
        run: |
          echo "Generating internationalization files..."
          # 运行 flutter gen-l10n 生成国际化代码，如果失败则退出并提示
          flutter gen-l10n
          # 检查生成结果
          echo "Internationalization files generated successfully. Files:"
          ls -la .dart_tool/flutter_gen/gen_l10n/
      
      - name: Stage and commit changes  
        run: |
          echo "Staging changes..."  
          # 输出提示信息，表示正在暂存文件
          git add pubspec.yaml lib/l10n/ .dart_tool/flutter_gen/gen_l10n/ l10n.yaml
          # 将文件添加到暂存区
          git status  
          # 显示暂存区状态，便于确认是否成功暂存
          echo "Configuring git identity..."  
          # 配置用户身份
          git config --local user.name "ITVAPP"  
          # 设置用户名
          git config --local user.email "actions@itvapp.net"  
          # 设置邮箱
          git commit -m "Update i18n files from CI [${{ github.run_id }}]" || echo "Nothing to commit"  
          # 提交更改，如果没有文件更改则输出提示
      
      - name: Push changes  
        # 使用 github-push-action 推送更改
        uses: ad-m/github-push-action@master  
        # 使用 GitHub 推送 Action 进行推送
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          # 使用 GitHub token 进行认证
          branch: main  
          # 目标分支，根据仓库实际情况替换
