name: Generate-pubspec.lock

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-pubspec-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Update pubspec.lock
        run: |
          echo "Cleaning Pub cache to ensure fresh dependency resolution..."
          flutter pub cache clean
          
          echo "Removing existing pubspec.lock to force full dependency resolution..."
          rm -f pubspec.lock
          
          echo "Analyzing potential dependency conflicts..."
          flutter pub outdated > pub_outdated_log.txt 2>&1
          echo "Dependency analysis output:"
          cat pub_outdated_log.txt
          
          echo "Running flutter pub get with verbose output to generate pubspec.lock..."
          flutter pub get -v > pub_get_verbose_log.txt 2>&1
          if [ $? -ne 0 ]; then
            echo "Error: flutter pub get failed. Analyzing conflicts..."
            echo "Searching for geolocator_android constraints in verbose log..."
            grep -i "geolocator_android" pub_get_verbose_log.txt > geolocator_conflicts.txt
            echo "Potential conflicts for geolocator_android:"
            cat geolocator_conflicts.txt
            echo "Generating dependency tree for further analysis..."
            flutter pub deps --style=compact > pub_deps_log.txt 2>&1
            echo "Dependency tree:"
            cat pub_deps_log.txt
            echo "Possible conflicting packages (searching for geolocator_android dependencies):"
            grep -B 5 -A 5 "geolocator_android" pub_deps_log.txt || echo "No direct dependencies found in tree"
            exit 1
          fi
          
          [ -f pubspec.lock ] || { echo "pubspec.lock not generated"; exit 1; }
          
          echo "Checking geolocator dependencies in pubspec.lock..."
          grep "geolocator:" pubspec.lock -A 4 || { echo "geolocator not found in pubspec.lock"; exit 1; }
          grep "geolocator_android:" pubspec.lock -A 4 || { echo "geolocator_android not found in pubspec.lock"; exit 1; }
          grep "geolocator_apple:" pubspec.lock -A 4 || { echo "geolocator_apple not found in pubspec.lock"; exit 1; }
          
          # 确保 geolocator_android 版本 >= 6.0.0
          if ! grep -E '^\s*version: "6\.[0-9]+\.[0-9]+.*"' pubspec.lock; then
            echo "Error: geolocator_android version is not >= 6.0.0, required for geolocator: 14.0.0"
            echo "Current version:"
            grep "geolocator_android:" pubspec.lock -A 4
            echo "Running flutter pub deps for debugging..."
            flutter pub deps --style=compact > pub_deps_log.txt 2>&1
            cat pub_deps_log.txt
            exit 1
          fi
          
          # 确保 geolocator_apple 版本 >= 2.3.7
          if ! grep -E '^\s*version: "2\.3\.[7-9]"' pubspec.lock && ! grep -E '^\s*version: "2\.[4-9]\.[0-9]+.*"' pubspec.lock; then
            echo "Error: geolocator_apple version is not >= 2.3.7, required for geolocator: 14.0.0"
            echo "Current version:"
            grep "geolocator_apple:" pubspec.lock -A 4
            cat pub_deps_log.txt
            exit 1
          fi
          
          echo "pubspec.lock generated successfully. Content preview:"
          head -n 20 pubspec.lock
      
      - name: Stage and commit pubspec.lock
        run: |
          echo "Staging pubspec.lock..."
          git add pubspec.lock
          git status
          echo "Configuring git identity..."
          git config --local user.name "ITVAPP"
          git config --local user.email "actions@itvapp.net"
          git commit -m "Update pubspec.lock from CI [${{ github.run_id }}]" || echo "Nothing to commit"
      
      - name: Push pubspec.lock
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
